-- ============================================================================
-- OBSOLETO — no ejecutar. Este archivo ya no aplica nada.
--
-- Es un archivo de solo comentarios a propósito: si alguien lo corre por
-- costumbre (`psql -f deploy/production-migration.sql`), no pasa nada. Antes
-- contenía la migración 0028 suelta, y volver a ejecutarla hoy sería, en el
-- mejor caso, ruido.
--
-- ── Cómo se aplican las migraciones ahora ───────────────────────────────────
--
-- A mano, con el CLI, y SIEMPRE ANTES de mergear el PR que las trae. Vercel
-- despliega `main` automáticamente, así que mergear sin haber migrado deja el
-- código nuevo corriendo contra el esquema viejo:
--
--     supabase db push --dry-run --linked   # ver primero qué se aplicaría
--     supabase db push --linked
--
-- Existe un job `deploy` en .github/workflows/ci.yml que automatiza este orden
-- (tests → migraciones → build → deploy), pero está DESACTIVADO: el build
-- desde CI produjo un artefacto roto. Ver el bloque de comentarios de ese job
-- antes de re-habilitarlo.
--
-- Si una migración quedó aplicada fuera de orden, se corrige el historial con
-- `supabase migration repair --status applied <version> --linked`.
--
-- ── Por qué existía este archivo ────────────────────────────────────────────
--
-- Se aplicaban las migraciones a mano y este archivo era el guion a pegar en
-- el SQL Editor de Supabase. El problema es que nada obligaba a mantenerlo al
-- día: quedó congelado en la 0028 mientras el repo llegaba a la 0039, once
-- migraciones después.
--
-- El 19-ago-2026 eso costó una caída: se mergeó la 0039 (creaba
-- transcription_usage), Vercel desplegó el código nuevo enseguida y la
-- migración nunca se aplicó. `/consultations/[id]/live` —la consulta en vivo,
-- la función central del producto— quedó lanzando contra una tabla que no
-- existía, junto con /settings, /settings/plan y la consola de plataforma.
--
-- ── Si hace falta aplicar algo fuera del flujo normal ───────────────────────
--
-- Para un hotfix o una migración fuera de orden, usar el CLI contra el
-- proyecto vinculado, nunca un archivo suelto:
--
--     supabase db push --dry-run --linked   # ver primero qué se aplicaría
--     supabase db push --linked
--
-- Si una migración quedó aplicada fuera de orden, se corrige el historial con
-- `supabase migration repair --status applied <version> --linked`, no
-- reescribiendo migraciones ya aplicadas.
-- ============================================================================
