-- ============================================================================
-- OBSOLETO — no ejecutar. Este archivo ya no aplica nada.
--
-- Es un archivo de solo comentarios a propósito: si alguien lo corre por
-- costumbre (`psql -f deploy/production-migration.sql`), no pasa nada. Antes
-- contenía la migración 0028 suelta, y volver a ejecutarla hoy sería, en el
-- mejor caso, ruido.
--
-- ── Cómo se aplican las migraciones ahora ───────────────────────────────────
--
-- Automáticamente, desde CI, al mergear a `main`. El job `deploy` de
-- .github/workflows/ci.yml corre en este orden:
--
--     tests → supabase db push → build → deploy a Vercel → smoke check
--
-- Las migraciones van ANTES del despliegue, y si fallan el código nuevo nunca
-- llega a producción. No hay que aplicar nada a mano ni mantener este archivo
-- sincronizado.
--
-- El auto-deploy de `main` en Vercel está desactivado (git.deploymentEnabled
-- en vercel.json) justamente para que producción se despliegue solo por esa
-- vía, con el orden garantizado.
--
-- ── Por qué existía este archivo ────────────────────────────────────────────
--
-- Se aplicaban las migraciones a mano y este archivo era el guion a pegar en
-- el SQL Editor de Supabase. El problema es que nada obligaba a mantenerlo al
-- día: quedó congelado en la 0028 mientras el repo llegaba a la 0039, once
-- migraciones después.
--
-- El 19-ago-2026 eso costó una caída: se mergeó la 0039 (creaba
-- transcription_usage), Vercel desplegó el código nuevo enseguida y la
-- migración nunca se aplicó. `/consultations/[id]/live` —la consulta en vivo,
-- la función central del producto— quedó lanzando contra una tabla que no
-- existía, junto con /settings, /settings/plan y la consola de plataforma.
--
-- ── Si hace falta aplicar algo fuera del flujo normal ───────────────────────
--
-- Para un hotfix o una migración fuera de orden, usar el CLI contra el
-- proyecto vinculado, nunca un archivo suelto:
--
--     supabase db push --dry-run --linked   # ver primero qué se aplicaría
--     supabase db push --linked
--
-- Si una migración quedó aplicada fuera de orden, se corrige el historial con
-- `supabase migration repair --status applied <version> --linked`, no
-- reescribiendo migraciones ya aplicadas.
-- ============================================================================
